# Generated by Django 4.2.3 on 2023-08-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_cart_id_cart__cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='_cart_id',
            new_name='cart_id',
        ),
    ]
